# Generated by Django 6.0.1 on 2026-02-23 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=10000, verbose_name='Nombre Usuario')),
                ('nombre_torrent', models.CharField(max_length=10000, verbose_name='Nombre Torrent')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
                ('enlace', models.CharField(max_length=10000, verbose_name='Enlace')),
                ('tamano', models.CharField(max_length=100, verbose_name='Tamano')),
                ('fecha', models.CharField(max_length=100, verbose_name='Fecha')),
                ('seeders', models.CharField(max_length=100, verbose_name='Seeders')),
                ('leechers', models.CharField(max_length=100, verbose_name='Leechers')),
                ('likes', models.IntegerField(default=0, verbose_name='Likes')),
                ('dislikes', models.IntegerField(default=0, verbose_name='Dislikes')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='usuario')),
                ('email', models.EmailField(help_text='(Obligatorio)', max_length=100, unique=True, verbose_name='Correo electrónico')),
                ('imagen', models.CharField()),
                ('descripcion', models.TextField(default='Escriba su nueva descripción', max_length=350)),
                ('is_superuser', models.BooleanField(default=False, verbose_name='¿Es super usuario?')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Es staff?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ('-email',),
            },
        ),
        migrations.CreateModel(
            name='ResetPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
