# Generated by Django 6.0.1 on 2026-02-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_favorito', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InteractuanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Interactuan',
                'verbose_name_plural': 'Interactuan',
                'db_table': 'interactuan',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='usuario')),
                ('email', models.EmailField(help_text='(Obligatorio)', max_length=100, unique=True, verbose_name='Correo electrónico')),
                ('password', models.TextField(help_text='(Obligatorio)', unique=True)),
                ('imagen', models.TextField()),
                ('descripcion', models.TextField(max_length=350)),
                ('is_superuser', models.BooleanField(default=False, verbose_name='¿Es super usuario?')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Es staff?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ('-email',),
            },
        ),
    ]
