# Generated by Django 6.0.1 on 2026-02-25 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritomodel',
            old_name='enlace',
            new_name='magnet',
        ),
        migrations.RenameField(
            model_name='favoritomodel',
            old_name='tamano',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='favoritomodel',
            old_name='fecha',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='favoritomodel',
            old_name='nombre_torrent',
            new_name='title',
        ),
    ]
