# Generated by Django 6.0.1 on 2026-02-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_usermodel_imagen_alter_usermodel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='descripcion',
            field=models.TextField(default='Escriba su nueva descripción', max_length=350),
        ),
    ]
