# Generated by Django 6.0.1 on 2026-02-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TorrentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
                ('enlace', models.CharField(max_length=100, verbose_name='Enlace')),
                ('tamano', models.CharField(max_length=100, verbose_name='Tamano')),
                ('fecha', models.CharField(max_length=100, verbose_name='Fecha')),
                ('seeders', models.CharField(max_length=100, verbose_name='Seeders')),
                ('leechers', models.CharField(max_length=100, verbose_name='Leechers')),
            ],
            options={
                'verbose_name': 'Torrent',
                'verbose_name_plural': 'Torrents',
                'db_table': 'torrent',
            },
        ),
    ]
