# Generated by Django 6.0.1 on 2026-02-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_torrent', models.CharField(max_length=10000, verbose_name='Nombre de Torrent')),
                ('nombre_usuario', models.CharField(max_length=15, verbose_name='Nombre de Usuario')),
                ('imagen_usuario', models.CharField(verbose_name='Imagen de Usuario')),
                ('texto_usuario', models.TextField(blank=True, max_length=350, null=True, verbose_name='Texto de comentario')),
                ('fecha', models.DateField(verbose_name='Fecha de publicación')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'db_table': 'comentario',
            },
        ),
        migrations.CreateModel(
            name='TorrentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10000, verbose_name='Nombre')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
                ('enlace', models.CharField(max_length=10000, verbose_name='Enlace')),
                ('tamano', models.CharField(max_length=100, verbose_name='Tamano')),
                ('fecha', models.CharField(max_length=100, verbose_name='Fecha')),
                ('seeders', models.CharField(max_length=100, verbose_name='Seeders')),
                ('leechers', models.CharField(max_length=100, verbose_name='Leechers')),
            ],
            options={
                'verbose_name': 'Torrent',
                'verbose_name_plural': 'Torrents',
                'db_table': 'torrent',
            },
        ),
    ]
