# Generated by Django 6.0.1 on 2026-02-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Torrents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='torrentmodel',
            name='dislikes',
            field=models.CharField(default=0, max_length=100, verbose_name='Dislikes'),
        ),
        migrations.AddField(
            model_name='torrentmodel',
            name='likes',
            field=models.CharField(default=0, max_length=100, verbose_name='Likes'),
        ),
    ]
