# Generated by Django 6.0.1 on 2026-02-22 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Torrents', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariomodel',
            name='es_dislike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comentarios_dislikes', to='Users.favoritomodel', verbose_name='Dado Dislike'),
        ),
        migrations.AddField(
            model_name='comentariomodel',
            name='es_like',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comentarios_likes', to='Users.favoritomodel', verbose_name='Dado Like'),
        ),
    ]
