# Generated by Django 6.0.1 on 2026-02-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Torrents', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrentmodel',
            name='enlace',
            field=models.CharField(max_length=10000, verbose_name='Enlace'),
        ),
    ]
