# Generated by Django 6.0.1 on 2026-02-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Torrents', '0003_alter_torrentmodel_enlace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrentmodel',
            name='dislikes',
            field=models.IntegerField(default=0, verbose_name='Dislikes'),
        ),
        migrations.AlterField(
            model_name='torrentmodel',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Likes'),
        ),
        migrations.AlterField(
            model_name='torrentmodel',
            name='nombre',
            field=models.CharField(max_length=10000, verbose_name='Nombre'),
        ),
    ]
